// megafunction wizard: %ROM: 1-PORT%
// GENERATION: STANDARD
// VERSION: WM1.0
// MODULE: altsyncram 

// ============================================================
// File Name: title.v
// Megafunction Name(s):
// 			altsyncram
//
// Simulation Library Files(s):
// 			altera_mf
// ============================================================
// ************************************************************
// THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
//
// 17.0.0 Build 595 04/25/2017 SJ Lite Edition
// ************************************************************


//Copyright (C) 2017  Intel Corporation. All rights reserved.
//Your use of Intel Corporation's design tools, logic functions 
//and other software and tools, and its AMPP partner logic 
//functions, and any output files from any of the foregoing 
//(including device programming or simulation files), and any 
//associated documentation or information are expressly subject 
//to the terms and conditions of the Intel Program License 
//Subscription Agreement, the Intel Quartus Prime License Agreement,
//the Intel MegaCore Function License Agreement, or other 
//applicable license agreement, including, without limitation, 
//that your use is for the sole purpose of programming logic 
//devices manufactured by Intel and sold by Intel or its 
//authorized distributors.  Please refer to the applicable 
//agreement for further details.


//altsyncram ADDRESS_ACLR_A="NONE" CLOCK_ENABLE_INPUT_A="BYPASS" CLOCK_ENABLE_OUTPUT_A="BYPASS" DEVICE_FAMILY="Cyclone IV E" ENABLE_RUNTIME_MOD="NO" INIT_FILE="../title.mif" NUMWORDS_A=17286 OPERATION_MODE="ROM" OUTDATA_ACLR_A="NONE" OUTDATA_REG_A="CLOCK0" WIDTH_A=8 WIDTH_BYTEENA_A=1 WIDTHAD_A=15 address_a clock0 q_a
//VERSION_BEGIN 17.0 cbx_altera_syncram_nd_impl 2017:04:25:18:06:29:SJ cbx_altsyncram 2017:04:25:18:06:29:SJ cbx_cycloneii 2017:04:25:18:06:29:SJ cbx_lpm_add_sub 2017:04:25:18:06:29:SJ cbx_lpm_compare 2017:04:25:18:06:29:SJ cbx_lpm_decode 2017:04:25:18:06:29:SJ cbx_lpm_mux 2017:04:25:18:06:30:SJ cbx_mgl 2017:04:25:18:09:28:SJ cbx_nadder 2017:04:25:18:06:30:SJ cbx_stratix 2017:04:25:18:06:30:SJ cbx_stratixii 2017:04:25:18:06:30:SJ cbx_stratixiii 2017:04:25:18:06:30:SJ cbx_stratixv 2017:04:25:18:06:30:SJ cbx_util_mgl 2017:04:25:18:06:30:SJ  VERSION_END
// synthesis VERILOG_INPUT_VERSION VERILOG_2001
// altera message_off 10463



//lpm_decode DEVICE_FAMILY="Cyclone IV E" LPM_DECODES=3 LPM_WIDTH=2 data eq
//VERSION_BEGIN 17.0 cbx_cycloneii 2017:04:25:18:06:29:SJ cbx_lpm_add_sub 2017:04:25:18:06:29:SJ cbx_lpm_compare 2017:04:25:18:06:29:SJ cbx_lpm_decode 2017:04:25:18:06:29:SJ cbx_mgl 2017:04:25:18:09:28:SJ cbx_nadder 2017:04:25:18:06:30:SJ cbx_stratix 2017:04:25:18:06:30:SJ cbx_stratixii 2017:04:25:18:06:30:SJ  VERSION_END

//synthesis_resources = lut 4 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  title_decode
	( 
	data,
	eq) /* synthesis synthesis_clearbox=1 */;
	input   [1:0]  data;
	output   [2:0]  eq;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [1:0]  data;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [1:0]  data_wire;
	wire  [2:0]  eq_node;
	wire  [3:0]  eq_wire;
	wire  [2:0]  w_anode106w;
	wire  [2:0]  w_anode120w;
	wire  [2:0]  w_anode129w;
	wire  [2:0]  w_anode138w;

	assign
		data_wire = data,
		eq = eq_node,
		eq_node = eq_wire[2:0],
		eq_wire = {w_anode138w[2], w_anode129w[2], w_anode120w[2], w_anode106w[2]},
		w_anode106w = {(w_anode106w[1] & (~ data_wire[1])), (w_anode106w[0] & (~ data_wire[0])), 1'b1},
		w_anode120w = {(w_anode120w[1] & (~ data_wire[1])), (w_anode120w[0] & data_wire[0]), 1'b1},
		w_anode129w = {(w_anode129w[1] & data_wire[1]), (w_anode129w[0] & (~ data_wire[0])), 1'b1},
		w_anode138w = {(w_anode138w[1] & data_wire[1]), (w_anode138w[0] & data_wire[0]), 1'b1};
endmodule //title_decode


//lpm_mux DEVICE_FAMILY="Cyclone IV E" LPM_SIZE=3 LPM_WIDTH=8 LPM_WIDTHS=2 data result sel
//VERSION_BEGIN 17.0 cbx_lpm_mux 2017:04:25:18:06:30:SJ cbx_mgl 2017:04:25:18:09:28:SJ  VERSION_END

//synthesis_resources = lut 16 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
module  title_mux
	( 
	data,
	result,
	sel) /* synthesis synthesis_clearbox=1 */;
	input   [23:0]  data;
	output   [7:0]  result;
	input   [1:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri0   [23:0]  data;
	tri0   [1:0]  sel;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire  [7:0]  data0_wire;
	wire  [7:0]  data1_wire;
	wire  [7:0]  data2_wire;
	wire  [7:0]  result_node;

	assign
		data0_wire = (data[7:0] & {8{(~ sel[0])}}),
		data1_wire = (data[15:8] & {8{sel[0]}}),
		data2_wire = (data[23:16] & {8{sel[1]}}),
		result = result_node,
		result_node = (((data0_wire | data1_wire) & {8{(~ sel[1])}}) | data2_wire);
endmodule //title_mux

//synthesis_resources = lut 20 M9K 16 M9K 1 reg 4 
//synopsys translate_off
`timescale 1 ps / 1 ps
//synopsys translate_on
(* ALTERA_ATTRIBUTE = {"OPTIMIZE_POWER_DURING_SYNTHESIS=NORMAL_COMPILATION"} *)
module  title_altsyncram
	( 
	address_a,
	clock0,
	q_a) /* synthesis synthesis_clearbox=1 */;
	input   [14:0]  address_a;
	input   clock0;
	output   [7:0]  q_a;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1   clock0;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	reg	[1:0]	address_reg_a;
	reg	[1:0]	out_address_reg_a;
	wire  [2:0]   wire_rden_decode_eq;
	wire  [7:0]   wire_mux2_result;
	wire  [0:0]   wire_ram_block1a_0portadataout;
	wire  [0:0]   wire_ram_block1a_1portadataout;
	wire  [0:0]   wire_ram_block1a_2portadataout;
	wire  [0:0]   wire_ram_block1a_3portadataout;
	wire  [0:0]   wire_ram_block1a_4portadataout;
	wire  [0:0]   wire_ram_block1a_5portadataout;
	wire  [0:0]   wire_ram_block1a_6portadataout;
	wire  [0:0]   wire_ram_block1a_7portadataout;
	wire  [0:0]   wire_ram_block1a_8portadataout;
	wire  [0:0]   wire_ram_block1a_9portadataout;
	wire  [0:0]   wire_ram_block1a_10portadataout;
	wire  [0:0]   wire_ram_block1a_11portadataout;
	wire  [0:0]   wire_ram_block1a_12portadataout;
	wire  [0:0]   wire_ram_block1a_13portadataout;
	wire  [0:0]   wire_ram_block1a_14portadataout;
	wire  [0:0]   wire_ram_block1a_15portadataout;
	wire  [0:0]   wire_ram_block1a_16portadataout;
	wire  [0:0]   wire_ram_block1a_17portadataout;
	wire  [0:0]   wire_ram_block1a_18portadataout;
	wire  [0:0]   wire_ram_block1a_19portadataout;
	wire  [0:0]   wire_ram_block1a_20portadataout;
	wire  [0:0]   wire_ram_block1a_21portadataout;
	wire  [0:0]   wire_ram_block1a_22portadataout;
	wire  [0:0]   wire_ram_block1a_23portadataout;
	wire  [1:0]  address_a_sel;
	wire  [14:0]  address_a_wire;
	wire  [1:0]  rden_decode_addr_sel_a;

	// synopsys translate_off
	initial
		address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  address_reg_a <= address_a_sel;
	// synopsys translate_off
	initial
		out_address_reg_a = 0;
	// synopsys translate_on
	always @ ( posedge clock0)
		  out_address_reg_a <= address_reg_a;
	title_decode   rden_decode
	( 
	.data(rden_decode_addr_sel_a),
	.eq(wire_rden_decode_eq));
	title_mux   mux2
	( 
	.data({wire_ram_block1a_23portadataout[0], wire_ram_block1a_22portadataout[0], wire_ram_block1a_21portadataout[0], wire_ram_block1a_20portadataout[0], wire_ram_block1a_19portadataout[0], wire_ram_block1a_18portadataout[0], wire_ram_block1a_17portadataout[0], wire_ram_block1a_16portadataout[0], wire_ram_block1a_15portadataout[0], wire_ram_block1a_14portadataout[0], wire_ram_block1a_13portadataout[0], wire_ram_block1a_12portadataout[0], wire_ram_block1a_11portadataout[0], wire_ram_block1a_10portadataout[0], wire_ram_block1a_9portadataout[0], wire_ram_block1a_8portadataout[0], wire_ram_block1a_7portadataout[0], wire_ram_block1a_6portadataout[0], wire_ram_block1a_5portadataout[0], wire_ram_block1a_4portadataout[0], wire_ram_block1a_3portadataout[0], wire_ram_block1a_2portadataout[0], wire_ram_block1a_1portadataout[0], wire_ram_block1a_0portadataout[0]}),
	.result(wire_mux2_result),
	.sel(out_address_reg_a));
	cycloneive_ram_block   ram_block1a_0
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_0portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_0.clk0_core_clock_enable = "ena0",
		ram_block1a_0.clk0_input_clock_enable = "none",
		ram_block1a_0.clk0_output_clock_enable = "none",
		ram_block1a_0.connectivity_checking = "OFF",
		ram_block1a_0.init_file = "../title.mif",
		ram_block1a_0.init_file_layout = "port_a",
		ram_block1a_0.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_0.mem_init0 = 2048'h80000000000003F00000380000000000000000000000000001C00700000E3800E00000000000003C00000E00000000000000000000000000007001C000038E00380000000000000F00000380000000000000000000000000001C00700000E3800E00000000000000780000E00000000000000000000000000007001C0001C0E003800000000000001E0000380000000000000000000000000001C0070000703800E00000000000000780000E00000000000000000000000000007001C0001C0FFFF8000000000000001FFFFF80000000000000000000000000001FFFFFFFF803FFFE0000000000000007FFFFE00000000000000000000000000007FFFFFFFE00,
		ram_block1a_0.mem_init1 = 2048'hFFFF81C007800E0038007000C01FFFFE00FFFFFFFFFF81C007FFF001F800FF81FFFFE07001E003800E001C003007FFFF803FFFFFFFFFE07001FFFC007E0038000000001FFFF800E003FFFFFFFC000000000000000000001C007FFF001F800E0000000007FFFE000000FFFFFFFF0000000000000000000007001C000007E0038000000001FFFF8000003FFFFFFFC000000000000000000001C007000001F800E0000000000000E000000E00000000000000000000000000007001C000007E00380000000000003800000380000000000000000000000000001C007000001F800E0000000000000E000000E00000000000000000000000000007001C000007E003,
		ram_block1a_0.mem_init2 = 2048'h01C00780000038007000E000000F00000038000003C007000001F8000003C00003F001E000000E001C0038000003F000000E000003F001C000007E000003F00000FC00780000038007000F800000FE000003800001FC007000001F800000FC00003F001E000000E001C003E000003F800000E000007F001C000007E00001C7000071C007800E0038007000C7E0000E3F000038000071C007000001F8000071C0001C7001E003800E001C0031F800038FC0000E00001C7001C000007E00001C7000071C007800E0038007000C7E0000E3F000038000071C007000001F800FF81FFFFE07001E003800E001C003007FFFF803FFFFFFFFFE07001FFFC007E003FE07,
		ram_block1a_0.mem_init3 = 2048'h0780000038007000E003800F001C003800E003C007FFF001F800F001FFE0007001E000000E001C003800E003C007000E003800F001C000007E003C007FF8001C00780000038007000E003800F001C003800E003C007000001F800F001FFC0007001E000000E001C003800E003C007000E003800F001C000007E0000007000001FFFF80000038007000E000000F00000038000003C007000001F8000001C000007FFFE000000E001C0038000003C000000E000000F001C000007E0000007000001FFFF80000038007000E000000F00000038000003C007000001F8000001C000007001E000000E001C0038000003C000000E000000F001C000007E00000070000,
		ram_block1a_0.operation_mode = "rom",
		ram_block1a_0.port_a_address_clear = "none",
		ram_block1a_0.port_a_address_width = 13,
		ram_block1a_0.port_a_data_out_clear = "none",
		ram_block1a_0.port_a_data_out_clock = "clock0",
		ram_block1a_0.port_a_data_width = 1,
		ram_block1a_0.port_a_first_address = 0,
		ram_block1a_0.port_a_first_bit_number = 0,
		ram_block1a_0.port_a_last_address = 8191,
		ram_block1a_0.port_a_logical_ram_depth = 17286,
		ram_block1a_0.port_a_logical_ram_width = 8,
		ram_block1a_0.ram_block_type = "AUTO",
		ram_block1a_0.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_1
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_1portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_1.clk0_core_clock_enable = "ena0",
		ram_block1a_1.clk0_input_clock_enable = "none",
		ram_block1a_1.clk0_output_clock_enable = "none",
		ram_block1a_1.connectivity_checking = "OFF",
		ram_block1a_1.init_file = "../title.mif",
		ram_block1a_1.init_file_layout = "port_a",
		ram_block1a_1.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_1.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_1.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_1.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_1.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_1.operation_mode = "rom",
		ram_block1a_1.port_a_address_clear = "none",
		ram_block1a_1.port_a_address_width = 13,
		ram_block1a_1.port_a_data_out_clear = "none",
		ram_block1a_1.port_a_data_out_clock = "clock0",
		ram_block1a_1.port_a_data_width = 1,
		ram_block1a_1.port_a_first_address = 0,
		ram_block1a_1.port_a_first_bit_number = 1,
		ram_block1a_1.port_a_last_address = 8191,
		ram_block1a_1.port_a_logical_ram_depth = 17286,
		ram_block1a_1.port_a_logical_ram_width = 8,
		ram_block1a_1.ram_block_type = "AUTO",
		ram_block1a_1.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_2
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_2portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_2.clk0_core_clock_enable = "ena0",
		ram_block1a_2.clk0_input_clock_enable = "none",
		ram_block1a_2.clk0_output_clock_enable = "none",
		ram_block1a_2.connectivity_checking = "OFF",
		ram_block1a_2.init_file = "../title.mif",
		ram_block1a_2.init_file_layout = "port_a",
		ram_block1a_2.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_2.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_2.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_2.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_2.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_2.operation_mode = "rom",
		ram_block1a_2.port_a_address_clear = "none",
		ram_block1a_2.port_a_address_width = 13,
		ram_block1a_2.port_a_data_out_clear = "none",
		ram_block1a_2.port_a_data_out_clock = "clock0",
		ram_block1a_2.port_a_data_width = 1,
		ram_block1a_2.port_a_first_address = 0,
		ram_block1a_2.port_a_first_bit_number = 2,
		ram_block1a_2.port_a_last_address = 8191,
		ram_block1a_2.port_a_logical_ram_depth = 17286,
		ram_block1a_2.port_a_logical_ram_width = 8,
		ram_block1a_2.ram_block_type = "AUTO",
		ram_block1a_2.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_3
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_3portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_3.clk0_core_clock_enable = "ena0",
		ram_block1a_3.clk0_input_clock_enable = "none",
		ram_block1a_3.clk0_output_clock_enable = "none",
		ram_block1a_3.connectivity_checking = "OFF",
		ram_block1a_3.init_file = "../title.mif",
		ram_block1a_3.init_file_layout = "port_a",
		ram_block1a_3.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_3.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_3.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_3.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_3.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_3.operation_mode = "rom",
		ram_block1a_3.port_a_address_clear = "none",
		ram_block1a_3.port_a_address_width = 13,
		ram_block1a_3.port_a_data_out_clear = "none",
		ram_block1a_3.port_a_data_out_clock = "clock0",
		ram_block1a_3.port_a_data_width = 1,
		ram_block1a_3.port_a_first_address = 0,
		ram_block1a_3.port_a_first_bit_number = 3,
		ram_block1a_3.port_a_last_address = 8191,
		ram_block1a_3.port_a_logical_ram_depth = 17286,
		ram_block1a_3.port_a_logical_ram_width = 8,
		ram_block1a_3.ram_block_type = "AUTO",
		ram_block1a_3.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_4
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_4portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_4.clk0_core_clock_enable = "ena0",
		ram_block1a_4.clk0_input_clock_enable = "none",
		ram_block1a_4.clk0_output_clock_enable = "none",
		ram_block1a_4.connectivity_checking = "OFF",
		ram_block1a_4.init_file = "../title.mif",
		ram_block1a_4.init_file_layout = "port_a",
		ram_block1a_4.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_4.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_4.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_4.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_4.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_4.operation_mode = "rom",
		ram_block1a_4.port_a_address_clear = "none",
		ram_block1a_4.port_a_address_width = 13,
		ram_block1a_4.port_a_data_out_clear = "none",
		ram_block1a_4.port_a_data_out_clock = "clock0",
		ram_block1a_4.port_a_data_width = 1,
		ram_block1a_4.port_a_first_address = 0,
		ram_block1a_4.port_a_first_bit_number = 4,
		ram_block1a_4.port_a_last_address = 8191,
		ram_block1a_4.port_a_logical_ram_depth = 17286,
		ram_block1a_4.port_a_logical_ram_width = 8,
		ram_block1a_4.ram_block_type = "AUTO",
		ram_block1a_4.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_5
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_5portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_5.clk0_core_clock_enable = "ena0",
		ram_block1a_5.clk0_input_clock_enable = "none",
		ram_block1a_5.clk0_output_clock_enable = "none",
		ram_block1a_5.connectivity_checking = "OFF",
		ram_block1a_5.init_file = "../title.mif",
		ram_block1a_5.init_file_layout = "port_a",
		ram_block1a_5.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_5.mem_init0 = 2048'h000000000000000FFFFFC000000000000000000000000000003FF8FFFFF007FF0000000000000003FFFFF000000000000000000000000000000FFE3FFFFC01FFC000000000000000FFFFFC000000000000000000000000000003FF8FFFFF007FF00000000000000007FFFF000000000000000000000000000000FFE3FFFE001FFC0000000000000001FFFFC000000000000000000000000000003FF8FFFF8007FF00000000000000007FFFF000000000000000000000000000000FFE3FFFE00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_5.mem_init1 = 2048'h0000003FF87FF1FFC7FF8FFF00000000000000000000003FF8000FFE07FF00000000000FFE1FFC7FF1FFE3FFC0000000000000000000000FFE0003FF81FFC000000000000007FF1FFC000000000000000000000000000003FF8000FFE07FF000000000000001FFFFFF000000000000000000000000000000FFE3FFFFF81FFC000000000000007FFFFFC000000000000000000000000000003FF8FFFFFE07FF000000000000001FFFFFF000000000000000000000000000000FFE3FFFFF81FFC000000000000007FFFFFC000000000000000000000000000003FF8FFFFFE07FF000000000000001FFFFFF000000000000000000000000000000FFE3FFFFF81FFC,
		ram_block1a_5.mem_init2 = 2048'hFE3FF87FFFFFC7FF8FFF1FFFFFF0FFFFFFC7FFFFFC3FF8FFFFFE07FFFFFC3FFFFC0FFE1FFFFFF1FFE3FFC7FFFFFC0FFFFFF1FFFFFC0FFE3FFFFF81FFFFFC0FFFFF03FF87FFFFFC7FF8FFF07FFFFF01FFFFFC7FFFFE03FF8FFFFFE07FFFFF03FFFFC0FFE1FFFFFF1FFE3FFC1FFFFFC07FFFFF1FFFFF80FFE3FFFFF81FFFFE00FFFF803FF87FF1FFC7FF8FFF001FFFF000FFFFC7FFFF803FF8FFFFFE07FFFF803FFFE00FFE1FFC7FF1FFE3FFC007FFFC003FFFF1FFFFE00FFE3FFFFF81FFFFE00FFFF803FF87FF1FFC7FF8FFF001FFFF000FFFFC7FFFF803FF8FFFFFE07FF00000000000FFE1FFC7FF1FFE3FFC0000000000000000000000FFE0003FF81FFC0000,
		ram_block1a_5.mem_init3 = 2048'hF87FFFFFC7FF8FFF1FFC7FF0FFE3FFC7FF1FFC3FF8000FFE07FF0FFE001FFF8FFE1FFFFFF1FFE3FFC7FF1FFC3FF8FFF1FFC7FF0FFE3FFFFF81FFC3FF8007FFE3FF87FFFFFC7FF8FFF1FFC7FF0FFE3FFC7FF1FFC3FF8FFFFFE07FF0FFE003FFF8FFE1FFFFFF1FFE3FFC7FF1FFC3FF8FFF1FFC7FF0FFE3FFFFF81FFFFFF8FFFFFE00007FFFFFC7FF8FFF1FFFFFF0FFFFFFC7FFFFFC3FF8FFFFFE07FFFFFE3FFFFF80001FFFFFF1FFE3FFC7FFFFFC3FFFFFF1FFFFFF0FFE3FFFFF81FFFFFF8FFFFFE00007FFFFFC7FF8FFF1FFFFFF0FFFFFFC7FFFFFC3FF8FFFFFE07FFFFFE3FFFFF8FFE1FFFFFF1FFE3FFC7FFFFFC3FFFFFF1FFFFFF0FFE3FFFFF81FFFFFF8FFFF,
		ram_block1a_5.operation_mode = "rom",
		ram_block1a_5.port_a_address_clear = "none",
		ram_block1a_5.port_a_address_width = 13,
		ram_block1a_5.port_a_data_out_clear = "none",
		ram_block1a_5.port_a_data_out_clock = "clock0",
		ram_block1a_5.port_a_data_width = 1,
		ram_block1a_5.port_a_first_address = 0,
		ram_block1a_5.port_a_first_bit_number = 5,
		ram_block1a_5.port_a_last_address = 8191,
		ram_block1a_5.port_a_logical_ram_depth = 17286,
		ram_block1a_5.port_a_logical_ram_width = 8,
		ram_block1a_5.ram_block_type = "AUTO",
		ram_block1a_5.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_6
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_6portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_6.clk0_core_clock_enable = "ena0",
		ram_block1a_6.clk0_input_clock_enable = "none",
		ram_block1a_6.clk0_output_clock_enable = "none",
		ram_block1a_6.connectivity_checking = "OFF",
		ram_block1a_6.init_file = "../title.mif",
		ram_block1a_6.init_file_layout = "port_a",
		ram_block1a_6.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_6.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_6.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_6.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_6.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_6.operation_mode = "rom",
		ram_block1a_6.port_a_address_clear = "none",
		ram_block1a_6.port_a_address_width = 13,
		ram_block1a_6.port_a_data_out_clear = "none",
		ram_block1a_6.port_a_data_out_clock = "clock0",
		ram_block1a_6.port_a_data_width = 1,
		ram_block1a_6.port_a_first_address = 0,
		ram_block1a_6.port_a_first_bit_number = 6,
		ram_block1a_6.port_a_last_address = 8191,
		ram_block1a_6.port_a_logical_ram_depth = 17286,
		ram_block1a_6.port_a_logical_ram_width = 8,
		ram_block1a_6.ram_block_type = "AUTO",
		ram_block1a_6.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_7
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[0]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_7portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_7.clk0_core_clock_enable = "ena0",
		ram_block1a_7.clk0_input_clock_enable = "none",
		ram_block1a_7.clk0_output_clock_enable = "none",
		ram_block1a_7.connectivity_checking = "OFF",
		ram_block1a_7.init_file = "../title.mif",
		ram_block1a_7.init_file_layout = "port_a",
		ram_block1a_7.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_7.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_7.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_7.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_7.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_7.operation_mode = "rom",
		ram_block1a_7.port_a_address_clear = "none",
		ram_block1a_7.port_a_address_width = 13,
		ram_block1a_7.port_a_data_out_clear = "none",
		ram_block1a_7.port_a_data_out_clock = "clock0",
		ram_block1a_7.port_a_data_width = 1,
		ram_block1a_7.port_a_first_address = 0,
		ram_block1a_7.port_a_first_bit_number = 7,
		ram_block1a_7.port_a_last_address = 8191,
		ram_block1a_7.port_a_logical_ram_depth = 17286,
		ram_block1a_7.port_a_logical_ram_width = 8,
		ram_block1a_7.ram_block_type = "AUTO",
		ram_block1a_7.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_8
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_8portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_8.clk0_core_clock_enable = "ena0",
		ram_block1a_8.clk0_input_clock_enable = "none",
		ram_block1a_8.clk0_output_clock_enable = "none",
		ram_block1a_8.connectivity_checking = "OFF",
		ram_block1a_8.init_file = "../title.mif",
		ram_block1a_8.init_file_layout = "port_a",
		ram_block1a_8.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_8.mem_init0 = 2048'h0E0038000000E003800F001C003800E003C007007001F800F0018018007001E003800E0000003800E003C007000E003800F001C01C007E003C006006001C007800E0038000000E003800F001C003800E003C007007001F800F0018038007001E003800E0000003800E003C007000E003800F001C01C007E003C00603E001C007800E0038000000E003800F001C003800E003C007FFF001F800F00180F8007001E003800E0000003800E003C007000E003800F001FFFC007E003C007FFE001C00780000038007000E003800F001C003800E003C007FFF001F800F001FFF8007001E000000E001C003800E003C007000E003800F001FFFC007E003C007FFE001C0,
		ram_block1a_8.mem_init1 = 2048'h38007FF0F800000FE000003800001FC007007001F800000F8018007001FC00000E001FFC3E000003F800000E000007F001C01C007E000001E006001C007E0000038000038F800000FE000003800001FC007007001F80000018018007001E000000E00000FF8000003C000000E000000F001C01C007E0000006006001C0078000003800003FE000000F00000038000003C007007001F80000018018007001E000000E000001F8000003C000000E000000F001C01C007E0000006006001C00780000038000007E000000F00000038000003C007007001F80000018018007001E000000E000001F8000003C000000E000000F001C01C007E003C006006001C00780,
		ram_block1a_8.mem_init2 = 2048'h0180007F800E03FC003FFFFF01FFFF007FFFFFFFFF80001FFFFFFFC07FFFFE000060001FE00380FF000FFFFFC07FFFC01FFFFFFFFFF80007FFFFFFF0FFFFFF800018003FF800E1FFC003FFFFFE1FFFF007FFFFFFFFFE0001FFFFFFFC3FFFFFE00006000FFE00387FF000FFFFFF87FFFC01FFFFFFFFFF80007FFFFFFF0FFFFFF800038003FF800E1FFC003FFFFFE1FFFF007FFFF800007C0018007001FF80000E001FE007C00003FE00000E00001FF001C01C007E00001F0006001C007FE000038007F801F00000FF800003800007FC007007001F800007E0018007001FF00000E001FE007C00003FE00000E00001FF001C01C007E000003E006001C007F00000,
		ram_block1a_8.mem_init3 = 2048'h0003FFFE000FFFF0000000000000000000000000000000000000000000F800600000E0038003000C0000000000000000000000000000000000000000003E001800003800E000C0030000000000000000000000000000000000000000000F800600000E0038003000C000000000000000000000000000000000000000001F0001800003800E000C0030000000000000000000000000000000000000000007C000600000E0038003000C000000000000000000000000000000000000000001F0001800003800E000C003000000000000000003FFFFF80001FFFFFFFC07FFFFE000060001FE00380FF000FFFFFC07FFFC01FFFFFFFFFE00007FFFFFFF01FFFFF800,
		ram_block1a_8.operation_mode = "rom",
		ram_block1a_8.port_a_address_clear = "none",
		ram_block1a_8.port_a_address_width = 13,
		ram_block1a_8.port_a_data_out_clear = "none",
		ram_block1a_8.port_a_data_out_clock = "clock0",
		ram_block1a_8.port_a_data_width = 1,
		ram_block1a_8.port_a_first_address = 8192,
		ram_block1a_8.port_a_first_bit_number = 0,
		ram_block1a_8.port_a_last_address = 16383,
		ram_block1a_8.port_a_logical_ram_depth = 17286,
		ram_block1a_8.port_a_logical_ram_width = 8,
		ram_block1a_8.ram_block_type = "AUTO",
		ram_block1a_8.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_9
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_9portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_9.clk0_core_clock_enable = "ena0",
		ram_block1a_9.clk0_input_clock_enable = "none",
		ram_block1a_9.clk0_output_clock_enable = "none",
		ram_block1a_9.connectivity_checking = "OFF",
		ram_block1a_9.init_file = "../title.mif",
		ram_block1a_9.init_file_layout = "port_a",
		ram_block1a_9.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_9.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_9.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_9.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_9.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_9.operation_mode = "rom",
		ram_block1a_9.port_a_address_clear = "none",
		ram_block1a_9.port_a_address_width = 13,
		ram_block1a_9.port_a_data_out_clear = "none",
		ram_block1a_9.port_a_data_out_clock = "clock0",
		ram_block1a_9.port_a_data_width = 1,
		ram_block1a_9.port_a_first_address = 8192,
		ram_block1a_9.port_a_first_bit_number = 1,
		ram_block1a_9.port_a_last_address = 16383,
		ram_block1a_9.port_a_logical_ram_depth = 17286,
		ram_block1a_9.port_a_logical_ram_width = 8,
		ram_block1a_9.ram_block_type = "AUTO",
		ram_block1a_9.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_10
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_10portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_10.clk0_core_clock_enable = "ena0",
		ram_block1a_10.clk0_input_clock_enable = "none",
		ram_block1a_10.clk0_output_clock_enable = "none",
		ram_block1a_10.connectivity_checking = "OFF",
		ram_block1a_10.init_file = "../title.mif",
		ram_block1a_10.init_file_layout = "port_a",
		ram_block1a_10.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_10.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_10.operation_mode = "rom",
		ram_block1a_10.port_a_address_clear = "none",
		ram_block1a_10.port_a_address_width = 13,
		ram_block1a_10.port_a_data_out_clear = "none",
		ram_block1a_10.port_a_data_out_clock = "clock0",
		ram_block1a_10.port_a_data_width = 1,
		ram_block1a_10.port_a_first_address = 8192,
		ram_block1a_10.port_a_first_bit_number = 2,
		ram_block1a_10.port_a_last_address = 16383,
		ram_block1a_10.port_a_logical_ram_depth = 17286,
		ram_block1a_10.port_a_logical_ram_width = 8,
		ram_block1a_10.ram_block_type = "AUTO",
		ram_block1a_10.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_11
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_11portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_11.clk0_core_clock_enable = "ena0",
		ram_block1a_11.clk0_input_clock_enable = "none",
		ram_block1a_11.clk0_output_clock_enable = "none",
		ram_block1a_11.connectivity_checking = "OFF",
		ram_block1a_11.init_file = "../title.mif",
		ram_block1a_11.init_file_layout = "port_a",
		ram_block1a_11.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_11.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_11.operation_mode = "rom",
		ram_block1a_11.port_a_address_clear = "none",
		ram_block1a_11.port_a_address_width = 13,
		ram_block1a_11.port_a_data_out_clear = "none",
		ram_block1a_11.port_a_data_out_clock = "clock0",
		ram_block1a_11.port_a_data_width = 1,
		ram_block1a_11.port_a_first_address = 8192,
		ram_block1a_11.port_a_first_bit_number = 3,
		ram_block1a_11.port_a_last_address = 16383,
		ram_block1a_11.port_a_logical_ram_depth = 17286,
		ram_block1a_11.port_a_logical_ram_width = 8,
		ram_block1a_11.ram_block_type = "AUTO",
		ram_block1a_11.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_12
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_12portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_12.clk0_core_clock_enable = "ena0",
		ram_block1a_12.clk0_input_clock_enable = "none",
		ram_block1a_12.clk0_output_clock_enable = "none",
		ram_block1a_12.connectivity_checking = "OFF",
		ram_block1a_12.init_file = "../title.mif",
		ram_block1a_12.init_file_layout = "port_a",
		ram_block1a_12.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_12.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_12.operation_mode = "rom",
		ram_block1a_12.port_a_address_clear = "none",
		ram_block1a_12.port_a_address_width = 13,
		ram_block1a_12.port_a_data_out_clear = "none",
		ram_block1a_12.port_a_data_out_clock = "clock0",
		ram_block1a_12.port_a_data_width = 1,
		ram_block1a_12.port_a_first_address = 8192,
		ram_block1a_12.port_a_first_bit_number = 4,
		ram_block1a_12.port_a_last_address = 16383,
		ram_block1a_12.port_a_logical_ram_depth = 17286,
		ram_block1a_12.port_a_logical_ram_width = 8,
		ram_block1a_12.ram_block_type = "AUTO",
		ram_block1a_12.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_13
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_13portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_13.clk0_core_clock_enable = "ena0",
		ram_block1a_13.clk0_input_clock_enable = "none",
		ram_block1a_13.clk0_output_clock_enable = "none",
		ram_block1a_13.connectivity_checking = "OFF",
		ram_block1a_13.init_file = "../title.mif",
		ram_block1a_13.init_file_layout = "port_a",
		ram_block1a_13.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_13.mem_init0 = 2048'hF1FFC7FFFFFF1FFC7FF0FFE3FFC7FF1FFC3FF8000FFE07FF0FFE0007FF8FFE1FFC7FF1FFFFFFC7FF1FFC3FF8FFF1FFC7FF0FFE0003FF81FFC3FF8001FFE3FF87FF1FFC7FFFFFF1FFC7FF0FFE3FFC7FF1FFC3FF8000FFE07FF0FFE0007FF8FFE1FFC7FF1FFFFFFC7FF1FFC3FF8FFF1FFC7FF0FFE0003FF81FFC3FF8001FFE3FF87FF1FFC7FFFFFF1FFC7FF0FFE3FFC7FF1FFC3FF8000FFE07FF0FFE0007FF8FFE1FFC7FF1FFFFFFC7FF1FFC3FF8FFF1FFC7FF0FFE0003FF81FFC3FF8001FFE3FF87FFFFFC7FF8FFF1FFC7FF0FFE3FFC7FF1FFC3FF8000FFE07FF0FFE0007FF8FFE1FFFFFF1FFE3FFC7FF1FFC3FF8FFF1FFC7FF0FFE0003FF81FFC3FF8001FFE3F,
		ram_block1a_13.mem_init1 = 2048'hC7FF800007FFFFF01FFFFFC7FFFFE03FF8000FFE07FFFFF00007FF8FFE03FFFFF1FFE00001FFFFFC07FFFFF1FFFFF80FFE0003FF81FFFFFE0001FFE3FF81FFFFFC7FFFFC007FFFFF01FFFFFC7FFFFE03FF8000FFE07FFFFFE0007FF8FFE1FFFFFF1FFFFF007FFFFFC3FFFFFF1FFFFFF0FFE0003FF81FFFFFF8001FFE3FF87FFFFFC7FFFFC01FFFFFF0FFFFFFC7FFFFFC3FF8000FFE07FFFFFE0007FF8FFE1FFFFFF1FFFFFE07FFFFFC3FFFFFF1FFFFFF0FFE0003FF81FFFFFF8001FFE3FF87FFFFFC7FFFFF81FFFFFF0FFFFFFC7FFFFFC3FF8000FFE07FFFFFE0007FF8FFE1FFFFFF1FFFFFE07FFFFFC3FFFFFF1FFFFFF0FFE0003FF81FFC3FF8001FFE3FF87F,
		ram_block1a_13.mem_init2 = 2048'hFE0000007FF00003FFC0000000000000000000000000000000000000000001FFFF8000001FFC0000FFF00000000000000000000000000000000000000000007FFFE0000007FF00003FFC0000000000000000000000000000000000000000001FFFF8000001FFC0000FFF00000000000000000000000000000000000000000007FFFC0000007FF00003FFC0000000000000000007FFFF800007FF8FFE007FFFF1FFE000003FFFFC01FFFFF1FFFFE00FFE0003FF81FFFFE00001FFE3FF801FFFFC7FF800000FFFFF007FFFFC7FFFF803FF8000FFE07FFFF800007FF8FFE00FFFFF1FFE000003FFFFC01FFFFF1FFFFE00FFE0003FF81FFFFFC0001FFE3FF80FFFFF,
		ram_block1a_13.mem_init3 = 2048'h000000000000000000000000000000000000000000000000000000000007FF8000001FFC0000FFF000000000000000000000000000000000000000000001FFE0000007FF00003FFC000000000000000000000000000000000000000000007FF8000001FFC0000FFF00000000000000000000000000000000000000000000FFFE0000007FF00003FFC00000000000000000000000000000000000000000003FFF8000001FFC0000FFF00000000000000000000000000000000000000000000FFFE0000007FF00003FFC0000000000000000000000000000000000000000001FFFF8000001FFC0000FFF00000000000000000000000000000000000000000007FF,
		ram_block1a_13.operation_mode = "rom",
		ram_block1a_13.port_a_address_clear = "none",
		ram_block1a_13.port_a_address_width = 13,
		ram_block1a_13.port_a_data_out_clear = "none",
		ram_block1a_13.port_a_data_out_clock = "clock0",
		ram_block1a_13.port_a_data_width = 1,
		ram_block1a_13.port_a_first_address = 8192,
		ram_block1a_13.port_a_first_bit_number = 5,
		ram_block1a_13.port_a_last_address = 16383,
		ram_block1a_13.port_a_logical_ram_depth = 17286,
		ram_block1a_13.port_a_logical_ram_width = 8,
		ram_block1a_13.ram_block_type = "AUTO",
		ram_block1a_13.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_14
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_14portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_14.clk0_core_clock_enable = "ena0",
		ram_block1a_14.clk0_input_clock_enable = "none",
		ram_block1a_14.clk0_output_clock_enable = "none",
		ram_block1a_14.connectivity_checking = "OFF",
		ram_block1a_14.init_file = "../title.mif",
		ram_block1a_14.init_file_layout = "port_a",
		ram_block1a_14.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_14.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_14.operation_mode = "rom",
		ram_block1a_14.port_a_address_clear = "none",
		ram_block1a_14.port_a_address_width = 13,
		ram_block1a_14.port_a_data_out_clear = "none",
		ram_block1a_14.port_a_data_out_clock = "clock0",
		ram_block1a_14.port_a_data_width = 1,
		ram_block1a_14.port_a_first_address = 8192,
		ram_block1a_14.port_a_first_bit_number = 6,
		ram_block1a_14.port_a_last_address = 16383,
		ram_block1a_14.port_a_logical_ram_depth = 17286,
		ram_block1a_14.port_a_logical_ram_width = 8,
		ram_block1a_14.ram_block_type = "AUTO",
		ram_block1a_14.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_15
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[1]),
	.portaaddr({address_a_wire[12:0]}),
	.portadataout(wire_ram_block1a_15portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_15.clk0_core_clock_enable = "ena0",
		ram_block1a_15.clk0_input_clock_enable = "none",
		ram_block1a_15.clk0_output_clock_enable = "none",
		ram_block1a_15.connectivity_checking = "OFF",
		ram_block1a_15.init_file = "../title.mif",
		ram_block1a_15.init_file_layout = "port_a",
		ram_block1a_15.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_15.mem_init0 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.mem_init1 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.mem_init2 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.mem_init3 = 2048'h00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_15.operation_mode = "rom",
		ram_block1a_15.port_a_address_clear = "none",
		ram_block1a_15.port_a_address_width = 13,
		ram_block1a_15.port_a_data_out_clear = "none",
		ram_block1a_15.port_a_data_out_clock = "clock0",
		ram_block1a_15.port_a_data_width = 1,
		ram_block1a_15.port_a_first_address = 8192,
		ram_block1a_15.port_a_first_bit_number = 7,
		ram_block1a_15.port_a_last_address = 16383,
		ram_block1a_15.port_a_logical_ram_depth = 17286,
		ram_block1a_15.port_a_logical_ram_width = 8,
		ram_block1a_15.ram_block_type = "AUTO",
		ram_block1a_15.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_16
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_16portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_16.clk0_core_clock_enable = "ena0",
		ram_block1a_16.clk0_input_clock_enable = "none",
		ram_block1a_16.clk0_output_clock_enable = "none",
		ram_block1a_16.connectivity_checking = "OFF",
		ram_block1a_16.init_file = "../title.mif",
		ram_block1a_16.init_file_layout = "port_a",
		ram_block1a_16.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_16.mem_init0 = 904'h0000000000000000000000000003FFE00000FFFF8003FFFC00000000000000000000000000000000000000000007FFF800003FFFE000FFFF00000000000000000000000000000000000000000001FFFE00000FFFF8003FFFC00000000000000000000000000000000000000000007FFF80,
		ram_block1a_16.operation_mode = "rom",
		ram_block1a_16.port_a_address_clear = "none",
		ram_block1a_16.port_a_address_width = 10,
		ram_block1a_16.port_a_data_out_clear = "none",
		ram_block1a_16.port_a_data_out_clock = "clock0",
		ram_block1a_16.port_a_data_width = 1,
		ram_block1a_16.port_a_first_address = 16384,
		ram_block1a_16.port_a_first_bit_number = 0,
		ram_block1a_16.port_a_last_address = 17285,
		ram_block1a_16.port_a_logical_ram_depth = 17286,
		ram_block1a_16.port_a_logical_ram_width = 8,
		ram_block1a_16.ram_block_type = "AUTO",
		ram_block1a_16.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_17
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_17portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_17.clk0_core_clock_enable = "ena0",
		ram_block1a_17.clk0_input_clock_enable = "none",
		ram_block1a_17.clk0_output_clock_enable = "none",
		ram_block1a_17.connectivity_checking = "OFF",
		ram_block1a_17.init_file = "../title.mif",
		ram_block1a_17.init_file_layout = "port_a",
		ram_block1a_17.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_17.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_17.operation_mode = "rom",
		ram_block1a_17.port_a_address_clear = "none",
		ram_block1a_17.port_a_address_width = 10,
		ram_block1a_17.port_a_data_out_clear = "none",
		ram_block1a_17.port_a_data_out_clock = "clock0",
		ram_block1a_17.port_a_data_width = 1,
		ram_block1a_17.port_a_first_address = 16384,
		ram_block1a_17.port_a_first_bit_number = 1,
		ram_block1a_17.port_a_last_address = 17285,
		ram_block1a_17.port_a_logical_ram_depth = 17286,
		ram_block1a_17.port_a_logical_ram_width = 8,
		ram_block1a_17.ram_block_type = "AUTO",
		ram_block1a_17.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_18
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_18portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_18.clk0_core_clock_enable = "ena0",
		ram_block1a_18.clk0_input_clock_enable = "none",
		ram_block1a_18.clk0_output_clock_enable = "none",
		ram_block1a_18.connectivity_checking = "OFF",
		ram_block1a_18.init_file = "../title.mif",
		ram_block1a_18.init_file_layout = "port_a",
		ram_block1a_18.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_18.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_18.operation_mode = "rom",
		ram_block1a_18.port_a_address_clear = "none",
		ram_block1a_18.port_a_address_width = 10,
		ram_block1a_18.port_a_data_out_clear = "none",
		ram_block1a_18.port_a_data_out_clock = "clock0",
		ram_block1a_18.port_a_data_width = 1,
		ram_block1a_18.port_a_first_address = 16384,
		ram_block1a_18.port_a_first_bit_number = 2,
		ram_block1a_18.port_a_last_address = 17285,
		ram_block1a_18.port_a_logical_ram_depth = 17286,
		ram_block1a_18.port_a_logical_ram_width = 8,
		ram_block1a_18.ram_block_type = "AUTO",
		ram_block1a_18.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_19
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_19portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_19.clk0_core_clock_enable = "ena0",
		ram_block1a_19.clk0_input_clock_enable = "none",
		ram_block1a_19.clk0_output_clock_enable = "none",
		ram_block1a_19.connectivity_checking = "OFF",
		ram_block1a_19.init_file = "../title.mif",
		ram_block1a_19.init_file_layout = "port_a",
		ram_block1a_19.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_19.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_19.operation_mode = "rom",
		ram_block1a_19.port_a_address_clear = "none",
		ram_block1a_19.port_a_address_width = 10,
		ram_block1a_19.port_a_data_out_clear = "none",
		ram_block1a_19.port_a_data_out_clock = "clock0",
		ram_block1a_19.port_a_data_width = 1,
		ram_block1a_19.port_a_first_address = 16384,
		ram_block1a_19.port_a_first_bit_number = 3,
		ram_block1a_19.port_a_last_address = 17285,
		ram_block1a_19.port_a_logical_ram_depth = 17286,
		ram_block1a_19.port_a_logical_ram_width = 8,
		ram_block1a_19.ram_block_type = "AUTO",
		ram_block1a_19.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_20
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_20portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_20.clk0_core_clock_enable = "ena0",
		ram_block1a_20.clk0_input_clock_enable = "none",
		ram_block1a_20.clk0_output_clock_enable = "none",
		ram_block1a_20.connectivity_checking = "OFF",
		ram_block1a_20.init_file = "../title.mif",
		ram_block1a_20.init_file_layout = "port_a",
		ram_block1a_20.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_20.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_20.operation_mode = "rom",
		ram_block1a_20.port_a_address_clear = "none",
		ram_block1a_20.port_a_address_width = 10,
		ram_block1a_20.port_a_data_out_clear = "none",
		ram_block1a_20.port_a_data_out_clock = "clock0",
		ram_block1a_20.port_a_data_width = 1,
		ram_block1a_20.port_a_first_address = 16384,
		ram_block1a_20.port_a_first_bit_number = 4,
		ram_block1a_20.port_a_last_address = 17285,
		ram_block1a_20.port_a_logical_ram_depth = 17286,
		ram_block1a_20.port_a_logical_ram_width = 8,
		ram_block1a_20.ram_block_type = "AUTO",
		ram_block1a_20.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_21
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_21portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_21.clk0_core_clock_enable = "ena0",
		ram_block1a_21.clk0_input_clock_enable = "none",
		ram_block1a_21.clk0_output_clock_enable = "none",
		ram_block1a_21.connectivity_checking = "OFF",
		ram_block1a_21.init_file = "../title.mif",
		ram_block1a_21.init_file_layout = "port_a",
		ram_block1a_21.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_21.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_21.operation_mode = "rom",
		ram_block1a_21.port_a_address_clear = "none",
		ram_block1a_21.port_a_address_width = 10,
		ram_block1a_21.port_a_data_out_clear = "none",
		ram_block1a_21.port_a_data_out_clock = "clock0",
		ram_block1a_21.port_a_data_width = 1,
		ram_block1a_21.port_a_first_address = 16384,
		ram_block1a_21.port_a_first_bit_number = 5,
		ram_block1a_21.port_a_last_address = 17285,
		ram_block1a_21.port_a_logical_ram_depth = 17286,
		ram_block1a_21.port_a_logical_ram_width = 8,
		ram_block1a_21.ram_block_type = "AUTO",
		ram_block1a_21.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_22
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_22portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_22.clk0_core_clock_enable = "ena0",
		ram_block1a_22.clk0_input_clock_enable = "none",
		ram_block1a_22.clk0_output_clock_enable = "none",
		ram_block1a_22.connectivity_checking = "OFF",
		ram_block1a_22.init_file = "../title.mif",
		ram_block1a_22.init_file_layout = "port_a",
		ram_block1a_22.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_22.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_22.operation_mode = "rom",
		ram_block1a_22.port_a_address_clear = "none",
		ram_block1a_22.port_a_address_width = 10,
		ram_block1a_22.port_a_data_out_clear = "none",
		ram_block1a_22.port_a_data_out_clock = "clock0",
		ram_block1a_22.port_a_data_width = 1,
		ram_block1a_22.port_a_first_address = 16384,
		ram_block1a_22.port_a_first_bit_number = 6,
		ram_block1a_22.port_a_last_address = 17285,
		ram_block1a_22.port_a_logical_ram_depth = 17286,
		ram_block1a_22.port_a_logical_ram_width = 8,
		ram_block1a_22.ram_block_type = "AUTO",
		ram_block1a_22.lpm_type = "cycloneive_ram_block";
	cycloneive_ram_block   ram_block1a_23
	( 
	.clk0(clock0),
	.ena0(wire_rden_decode_eq[2]),
	.portaaddr({address_a_wire[9:0]}),
	.portadataout(wire_ram_block1a_23portadataout[0:0]),
	.portare(1'b1),
	.portbdataout()
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_off
	`endif
	,
	.clk1(1'b0),
	.clr0(1'b0),
	.clr1(1'b0),
	.ena1(1'b1),
	.ena2(1'b1),
	.ena3(1'b1),
	.portaaddrstall(1'b0),
	.portabyteenamasks({1{1'b1}}),
	.portadatain({1{1'b0}}),
	.portawe(1'b0),
	.portbaddr({1{1'b0}}),
	.portbaddrstall(1'b0),
	.portbbyteenamasks({1{1'b1}}),
	.portbdatain({1{1'b0}}),
	.portbre(1'b1),
	.portbwe(1'b0)
	`ifndef FORMAL_VERIFICATION
	// synopsys translate_on
	`endif
	// synopsys translate_off
	,
	.devclrn(1'b1),
	.devpor(1'b1)
	// synopsys translate_on
	);
	defparam
		ram_block1a_23.clk0_core_clock_enable = "ena0",
		ram_block1a_23.clk0_input_clock_enable = "none",
		ram_block1a_23.clk0_output_clock_enable = "none",
		ram_block1a_23.connectivity_checking = "OFF",
		ram_block1a_23.init_file = "../title.mif",
		ram_block1a_23.init_file_layout = "port_a",
		ram_block1a_23.logical_ram_name = "ALTSYNCRAM",
		ram_block1a_23.mem_init0 = 904'h0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
		ram_block1a_23.operation_mode = "rom",
		ram_block1a_23.port_a_address_clear = "none",
		ram_block1a_23.port_a_address_width = 10,
		ram_block1a_23.port_a_data_out_clear = "none",
		ram_block1a_23.port_a_data_out_clock = "clock0",
		ram_block1a_23.port_a_data_width = 1,
		ram_block1a_23.port_a_first_address = 16384,
		ram_block1a_23.port_a_first_bit_number = 7,
		ram_block1a_23.port_a_last_address = 17285,
		ram_block1a_23.port_a_logical_ram_depth = 17286,
		ram_block1a_23.port_a_logical_ram_width = 8,
		ram_block1a_23.ram_block_type = "AUTO",
		ram_block1a_23.lpm_type = "cycloneive_ram_block";
	assign
		address_a_sel = address_a[14:13],
		address_a_wire = address_a,
		q_a = wire_mux2_result,
		rden_decode_addr_sel_a = address_a_wire[14:13];
endmodule //title_altsyncram
//VALID FILE


// synopsys translate_off
`timescale 1 ps / 1 ps
// synopsys translate_on
module title (
	address,
	clock,
	q)/* synthesis synthesis_clearbox = 1 */;

	input	[14:0]  address;
	input	  clock;
	output	[7:0]  q;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_off
`endif
	tri1	  clock;
`ifndef ALTERA_RESERVED_QIS
// synopsys translate_on
`endif

	wire [7:0] sub_wire0;
	wire [7:0] q = sub_wire0[7:0];

	title_altsyncram	title_altsyncram_component (
				.address_a (address),
				.clock0 (clock),
				.q_a (sub_wire0));

endmodule

// ============================================================
// CNX file retrieval info
// ============================================================
// Retrieval info: PRIVATE: ADDRESSSTALL_A NUMERIC "0"
// Retrieval info: PRIVATE: AclrAddr NUMERIC "0"
// Retrieval info: PRIVATE: AclrByte NUMERIC "0"
// Retrieval info: PRIVATE: AclrOutput NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_ENABLE NUMERIC "0"
// Retrieval info: PRIVATE: BYTE_SIZE NUMERIC "8"
// Retrieval info: PRIVATE: BlankMemory NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_INPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: CLOCK_ENABLE_OUTPUT_A NUMERIC "0"
// Retrieval info: PRIVATE: Clken NUMERIC "0"
// Retrieval info: PRIVATE: IMPLEMENT_IN_LES NUMERIC "0"
// Retrieval info: PRIVATE: INIT_FILE_LAYOUT STRING "PORT_A"
// Retrieval info: PRIVATE: INIT_TO_SIM_X NUMERIC "0"
// Retrieval info: PRIVATE: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: PRIVATE: JTAG_ENABLED NUMERIC "0"
// Retrieval info: PRIVATE: JTAG_ID STRING "NONE"
// Retrieval info: PRIVATE: MAXIMUM_DEPTH NUMERIC "0"
// Retrieval info: PRIVATE: MIFfilename STRING "../title.mif"
// Retrieval info: PRIVATE: NUMWORDS_A NUMERIC "17286"
// Retrieval info: PRIVATE: RAM_BLOCK_TYPE NUMERIC "0"
// Retrieval info: PRIVATE: RegAddr NUMERIC "1"
// Retrieval info: PRIVATE: RegOutput NUMERIC "1"
// Retrieval info: PRIVATE: SYNTH_WRAPPER_GEN_POSTFIX STRING "1"
// Retrieval info: PRIVATE: SingleClock NUMERIC "1"
// Retrieval info: PRIVATE: UseDQRAM NUMERIC "0"
// Retrieval info: PRIVATE: WidthAddr NUMERIC "15"
// Retrieval info: PRIVATE: WidthData NUMERIC "8"
// Retrieval info: PRIVATE: rden NUMERIC "0"
// Retrieval info: LIBRARY: altera_mf altera_mf.altera_mf_components.all
// Retrieval info: CONSTANT: ADDRESS_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: CLOCK_ENABLE_INPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: CLOCK_ENABLE_OUTPUT_A STRING "BYPASS"
// Retrieval info: CONSTANT: INIT_FILE STRING "../title.mif"
// Retrieval info: CONSTANT: INTENDED_DEVICE_FAMILY STRING "Cyclone IV E"
// Retrieval info: CONSTANT: LPM_HINT STRING "ENABLE_RUNTIME_MOD=NO"
// Retrieval info: CONSTANT: LPM_TYPE STRING "altsyncram"
// Retrieval info: CONSTANT: NUMWORDS_A NUMERIC "17286"
// Retrieval info: CONSTANT: OPERATION_MODE STRING "ROM"
// Retrieval info: CONSTANT: OUTDATA_ACLR_A STRING "NONE"
// Retrieval info: CONSTANT: OUTDATA_REG_A STRING "CLOCK0"
// Retrieval info: CONSTANT: WIDTHAD_A NUMERIC "15"
// Retrieval info: CONSTANT: WIDTH_A NUMERIC "8"
// Retrieval info: CONSTANT: WIDTH_BYTEENA_A NUMERIC "1"
// Retrieval info: USED_PORT: address 0 0 15 0 INPUT NODEFVAL "address[14..0]"
// Retrieval info: USED_PORT: clock 0 0 0 0 INPUT VCC "clock"
// Retrieval info: USED_PORT: q 0 0 8 0 OUTPUT NODEFVAL "q[7..0]"
// Retrieval info: CONNECT: @address_a 0 0 15 0 address 0 0 15 0
// Retrieval info: CONNECT: @clock0 0 0 0 0 clock 0 0 0 0
// Retrieval info: CONNECT: q 0 0 8 0 @q_a 0 0 8 0
// Retrieval info: GEN_FILE: TYPE_NORMAL title.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL title.inc FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL title.cmp FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL title.bsf TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL title_inst.v FALSE
// Retrieval info: GEN_FILE: TYPE_NORMAL title_bb.v TRUE
// Retrieval info: GEN_FILE: TYPE_NORMAL title_syn.v TRUE
// Retrieval info: LIB_FILE: altera_mf
